# Use the alpine version of the official Python image with Python 3.10 as the base image
FROM python:3.9

# Set the working directory within the container
WORKDIR /app

# Copy the requirements file into the container at /app
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
# RUN pip install --upgrade pip
RUN pip install numpy==1.21.4
RUN pip install -r requirements.txt

# Copy the rest of the application code to the container
COPY . .

# Expose port 5000 for the Flask app
EXPOSE 5000

# Define environment variable (optional)
ENV FLASK_APP=app.py

# Start the Flask application
CMD ["python", "code.py"]